version: '2'
services:
  frontend:
    container_name: react_docker_template_client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1234:1234'
    image: ladams1776/react_docker_template_client
    volumes: ['/app']
